[tools]
node = "24"
pnpm = "11"
lazydocker = "latest"
lazygit = "latest"
"npm:pm2" = "latest"
opencode = "latest"
zellij = "latest"
# codex = "latest"
go = "latest"
golangci-lint = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
sqlite = "latest"
air = "latest"
opentofu = "latest"
k9s = "latest"
helm = "latest"
argocd = "latest"
kubeseal = "latest"
stern = "latest"
ripgrep = "latest"
pipx = "latest"
yamllint = "latest"
protoc = "latest"
protoc-gen-go-grpc = "latest"
protoc-gen-go = "latest"
postgres = "latest"
github-cli = "latest"
